# Generated by Django 5.1.1 on 2024-10-06 08:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('book', '0002_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowtransaction',
            old_name='returned_at',
            new_name='actual_return_date',
        ),
        migrations.RenameField(
            model_name='borrowtransaction',
            old_name='borrower',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='borrowed_at',
        ),
        migrations.RemoveField(
            model_name='borrowtransaction',
            name='due_date',
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='borrow_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='library',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='library.library'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='return_date',
            field=models.DateTimeField(default='2024-10-06 15:30:45-05:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='author.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='book.category'),
        ),
        migrations.DeleteModel(
            name='ReturnTransaction',
        ),
    ]
